from . import LAttackSource as _LAttackSource
from . import LRace as _LRace
from . import LSubRace as _LSubRace
from . import LUnitB as _LUnitB

ATTACK_SOURCE_ID_WEAPON = _LAttackSource.ATTACK_SOURCE_ID_WEAPON
ATTACK_SOURCE_ID_MIND = _LAttackSource.ATTACK_SOURCE_ID_MIND
ATTACK_SOURCE_ID_LIFE = _LAttackSource.ATTACK_SOURCE_ID_LIFE
ATTACK_SOURCE_ID_DEATH = _LAttackSource.ATTACK_SOURCE_ID_DEATH
ATTACK_SOURCE_ID_FIRE = _LAttackSource.ATTACK_SOURCE_ID_FIRE
ATTACK_SOURCE_ID_WATER = _LAttackSource.ATTACK_SOURCE_ID_WATER
ATTACK_SOURCE_ID_EARTH = _LAttackSource.ATTACK_SOURCE_ID_EARTH
ATTACK_SOURCE_ID_AIR = _LAttackSource.ATTACK_SOURCE_ID_AIR
ATTACK_SOURCE_ID_TO_NAME = _LAttackSource.ATTACK_SOURCE_ID_TO_NAME

LRACE_ID_EMPIRE = _LRace.LRACE_ID_EMPIRE
LRACE_ID_HORDES = _LRace.LRACE_ID_HORDES
LRACE_ID_DAMNED = _LRace.LRACE_ID_DAMNED
LRACE_ID_CLANS = _LRace.LRACE_ID_CLANS
LRACE_ID_NEUTRALS = _LRace.LRACE_ID_NEUTRALS
LRACE_ID_ELVES = _LRace.LRACE_ID_ELVES
LRACE_ID_TO_NAME = _LRace.LRACE_ID_TO_NAME

LSUBRACE_ID_NEUTRALS_0 = _LSubRace.LSUBRACE_ID_NEUTRALS_0
LSUBRACE_ID_PEOPLE = _LSubRace.LSUBRACE_ID_PEOPLE
LSUBRACE_ID_UNDEAD = _LSubRace.LSUBRACE_ID_UNDEAD
LSUBRACE_ID_DAMNED = _LSubRace.LSUBRACE_ID_DAMNED
LSUBRACE_ID_CLANS = _LSubRace.LSUBRACE_ID_CLANS
LSUBRACE_ID_NEUTRALS_5 = _LSubRace.LSUBRACE_ID_NEUTRALS_5
LSUBRACE_ID_NEUTRAL_PEOPLE = _LSubRace.LSUBRACE_ID_NEUTRAL_PEOPLE
LSUBRACE_ID_NEUTRAL_ELVES = _LSubRace.LSUBRACE_ID_NEUTRAL_ELVES
LSUBRACE_ID_GREEN_SKINNED = _LSubRace.LSUBRACE_ID_GREEN_SKINNED
LSUBRACE_ID_DRAGONS = _LSubRace.LSUBRACE_ID_DRAGONS
LSUBRACE_ID_INHABITANTS_OF_SWAMPS = _LSubRace.LSUBRACE_ID_INHABITANTS_OF_SWAMPS
LSUBRACE_ID_AQUATIC_INHABITANTS = _LSubRace.LSUBRACE_ID_AQUATIC_INHABITANTS
LSUBRACE_ID_BARBARIANS = _LSubRace.LSUBRACE_ID_BARBARIANS
LSUBRACE_ID_WOLVES = _LSubRace.LSUBRACE_ID_WOLVES
LSUBRACE_ID_ELVES = _LSubRace.LSUBRACE_ID_ELVES
LSUBRACE_ID_TO_NAME = _LSubRace.LSUBRACE_ID_TO_NAME

UNIT_B_ID_MELEE = _LUnitB.UNIT_B_ID_MELEE
UNIT_B_ID_RANGED = _LUnitB.UNIT_B_ID_RANGED
UNIT_B_ID_MAGE = _LUnitB.UNIT_B_ID_MAGE
UNIT_B_ID_TO_NAME = _LUnitB.UNIT_B_ID_TO_NAME