"""Constants for attack source IDs."""

ATTACK_SOURCE_ID_WEAPON = 0
ATTACK_SOURCE_ID_MIND = 1
ATTACK_SOURCE_ID_LIFE = 2
ATTACK_SOURCE_ID_DEATH = 3
ATTACK_SOURCE_ID_FIRE = 4
ATTACK_SOURCE_ID_WATER = 5
ATTACK_SOURCE_ID_EARTH = 6
ATTACK_SOURCE_ID_AIR = 7

ATTACK_SOURCE_ID_TO_NAME = {
    ATTACK_SOURCE_ID_WEAPON: "weapon",
    ATTACK_SOURCE_ID_MIND: "mind",
    ATTACK_SOURCE_ID_LIFE: "life",
    ATTACK_SOURCE_ID_DEATH: "death",
    ATTACK_SOURCE_ID_FIRE: "fire",
    ATTACK_SOURCE_ID_WATER: "water",
    ATTACK_SOURCE_ID_EARTH: "earth",
    ATTACK_SOURCE_ID_AIR: "air",
}