"""Constants for LSubRace IDs."""

LSUBRACE_ID_NEUTRALS_0 = 0
LSUBRACE_ID_PEOPLE = 1
LSUBRACE_ID_UNDEAD = 2
LSUBRACE_ID_DAMNED = 3
LSUBRACE_ID_CLANS = 4
LSUBRACE_ID_NEUTRALS_5 = 5
LSUBRACE_ID_NEUTRAL_PEOPLE = 6
LSUBRACE_ID_NEUTRAL_ELVES = 7
LSUBRACE_ID_GREEN_SKINNED = 8
LSUBRACE_ID_DRAGONS = 9
LSUBRACE_ID_INHABITANTS_OF_SWAMPS = 10
LSUBRACE_ID_AQUATIC_INHABITANTS = 11
LSUBRACE_ID_BARBARIANS = 12
LSUBRACE_ID_WOLVES = 13
LSUBRACE_ID_ELVES = 14

LSUBRACE_ID_TO_NAME = {
    LSUBRACE_ID_NEUTRALS_0: "neutrals",
    LSUBRACE_ID_PEOPLE: "people",
    LSUBRACE_ID_UNDEAD: "undead",
    LSUBRACE_ID_DAMNED: "damned",
    LSUBRACE_ID_CLANS: "clans",
    LSUBRACE_ID_NEUTRALS_5: "neutrals",
    LSUBRACE_ID_NEUTRAL_PEOPLE: "neutral people",
    LSUBRACE_ID_NEUTRAL_ELVES: "neutral elves",
    LSUBRACE_ID_GREEN_SKINNED: "green-skinned",
    LSUBRACE_ID_DRAGONS: "dragons",
    LSUBRACE_ID_INHABITANTS_OF_SWAMPS: "inhabitants of swamps",
    LSUBRACE_ID_AQUATIC_INHABITANTS: "aquatic inhabitants",
    LSUBRACE_ID_BARBARIANS: "barbarians",
    LSUBRACE_ID_WOLVES: "wolves",
    LSUBRACE_ID_ELVES: "elves",
}